<template>
  <div class="app-container">
    <header class="glass header">
      <div class="logo">
        <div class="logo-dot"></div>
        <h1>LED Matrix Studio</h1>
      </div>
      <div class="actions">
        <button class="btn primary" @click="exportCode">
          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"></path><polyline points="7 10 12 15 17 10"></polyline><line x1="12" y1="15" x2="12" y2="3"></line></svg>
          Export Code (ESP32)
        </button>
      </div>
    </header>

    <main class="main-content">
      <div class="workspace">
        <div class="toolbar-wrapper glass">
          <h3>Tools</h3>
          <Toolbar @generateBlink="onGenerateBlink" @generateCircle="onGenerateCircle" />
        </div>
        
        <div class="matrix-wrapper glass">
          <MatrixGrid />
        </div>
      </div>

      <div class="timeline-wrapper glass">
        <h3>Timeline & Animation</h3>
        <Timeline />
      </div>
    </main>
  </div>
</template>

<script setup lang="ts">
import MatrixGrid from './components/MatrixGrid.vue'
import Toolbar from './components/Toolbar.vue'
import Timeline from './components/Timeline.vue'
// Add store import explicitly in case auto-imports are not fully enabled during startup
import { useMatrixStore } from './composables/useMatrixStore'

const store = useMatrixStore()

// --- Generators ---
const onGenerateBlink = () => {
  const color = store.selectedColor.value
  
  // Gen Blink: Fill with color, then frame of black
  store.addFrame()
  store.fillGrid(color)
  
  store.addFrame()
  store.fillGrid(store.DEFAULT_COLOR)
}

const onGenerateCircle = () => {
  const color = store.selectedColor.value
  const maxRadius = Math.ceil(Math.sqrt(Math.pow(store.COLS/2, 2) + Math.pow(store.ROWS/2, 2)))
  const cx = store.COLS / 2
  const cy = store.ROWS / 2

  // Animate outwards
  for (let r = 0; r <= maxRadius; r++) {
    // Add a new empty frame for this step
    store.addFrame()
    store.clearGrid()
    
    // Draw circle of radius r
    for (let y = 0; y < store.ROWS; y++) {
      for (let x = 0; x < store.COLS; x++) {
        // Distance from center
        const dist = Math.sqrt(Math.pow(x - cx, 2) + Math.pow(y - cy, 2))
        // Thickness of 1-1.5 pixels
        if (Math.abs(dist - r) <= 1.2) {
          store.setPixel(y, x, color)
        }
      }
    }
  }
  
  // Optionally: select the first frame of the new animation
  store.selectFrame(store.frames.value.length - maxRadius - 1)
}

// --- Export Functionality ---
const exportCode = () => {
  let hCode = `// Generated by LED Matrix Studio\n`
  hCode += `#ifndef MATRIX_ANIMATION_H\n`
  hCode += `#define MATRIX_ANIMATION_H\n\n`
  hCode += `#include <stdint.h>\n`
  hCode += `#include <avr/pgmspace.h> // For PROGMEM on generic boards if needed\n\n`
  
  hCode += `const uint16_t FRAME_COUNT = ${store.frames.value.length};\n`
  hCode += `const uint8_t MATRIX_WIDTH = ${store.COLS};\n`
  hCode += `const uint8_t MATRIX_HEIGHT = ${store.ROWS};\n\n`

  // Store 1D array of uint32_t for each frame
  hCode += `const uint32_t matrix_animation[${store.frames.value.length}][${store.ROWS * store.COLS}] PROGMEM = {\n`
  
  store.frames.value.forEach((frame, fIndex) => {
    hCode += `  {\n    // Frame ${fIndex + 1}\n    `
    let colors: string[] = []
    
    for (let y = 0; y < store.ROWS; y++) {
      for (let x = 0; x < store.COLS; x++) {
        let hex = frame[y][x]
        // Convert #RRGGBB to 0xRRGGBB
        hex = '0x' + hex.substring(1).toUpperCase()
        colors.push(hex)
      }
    }
    
    // format to max 8 colors per line to keep it clean
    for (let i = 0; i < colors.length; i += 8) {
      hCode += colors.slice(i, i + 8).join(', ')
      if (i + 8 < colors.length) {
        hCode += ',\n    '
      }
    }
    hCode += `\n  }${fIndex < store.frames.value.length - 1 ? ',' : ''}\n`
  })

  hCode += `};\n\n#endif // MATRIX_ANIMATION_H\n`

  // Create a download link and trigger download for the generated header file
  const blob = new Blob([hCode], { type: 'text/plain' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = 'matrix_animation.h'
  a.click()
  URL.revokeObjectURL(url)
}
</script>

<style scoped>
.app-container {
  display: flex;
  flex-direction: column;
  height: 100vh;
  padding: 16px;
  gap: 16px;
  max-width: 1600px;
  margin: 0 auto;
}

.header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  padding: 16px 24px;
}

.logo {
  display: flex;
  align-items: center;
  gap: 12px;
}

.logo-dot {
  width: 12px;
  height: 12px;
  border-radius: 50%;
  background: var(--accent-color);
  box-shadow: 0 0 12px rgba(88, 166, 255, 0.8), 0 0 24px rgba(189, 86, 255, 0.4);
  animation: pulse 2s infinite ease-in-out;
}

@keyframes pulse {
  0% { transform: scale(0.95); opacity: 0.8; }
  50% { transform: scale(1.05); opacity: 1; }
  100% { transform: scale(0.95); opacity: 0.8; }
}

.header h1 {
  font-size: 1.4rem;
  font-weight: 600;
  letter-spacing: -0.5px;
  background: linear-gradient(90deg, #c9d1d9, #8b949e);
  -webkit-background-clip: text;
  -webkit-text-fill-color: transparent;
}

.main-content {
  display: flex;
  flex-direction: column;
  gap: 16px;
  flex: 1;
  min-height: 0;
}

.workspace {
  display: flex;
  gap: 16px;
  flex: 1;
  min-height: 0;
}

.toolbar-wrapper {
  width: 260px;
  padding: 20px;
  display: flex;
  flex-direction: column;
  gap: 16px;
  overflow-y: auto;
}

.toolbar-wrapper h3, .timeline-wrapper h3 {
  font-size: 0.85rem;
  text-transform: uppercase;
  letter-spacing: 1px;
  color: var(--text-secondary);
  margin-bottom: 8px;
}

.matrix-wrapper {
  flex: 1;
  display: flex;
  justify-content: center;
  align-items: center;
  padding: 24px;
  overflow: auto;
  position: relative;
}

.timeline-wrapper {
  height: 180px;
  padding: 16px 20px;
  display: flex;
  flex-direction: column;
}
</style>
